service_account_id    = "aje8vkfcaq1s60mtencd"
zone_name             = "ru-central1-a"
folder_id             = "b1gvurv45p81ocil3igg"
cloud_id              = "b1g3fuk1gs418fa34ng4"
vm_user               = "test_user"
ssh_key_path          = "id_rsa.pub"
k8s_version           = "1.26"